import type { Form } from '@/payload-types'

export const contactForm: Partial<Form> = {
  confirmationMessage: {
    root: {
      type: 'root',
      children: [
        {
          type: 'heading',
          children: [
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Thank you — your enquiry has been received.',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          tag: 'h2',
          version: 1,
        },
        {
          type: 'paragraph',
          children: [
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: "We'll be in touch within one business day to discuss your project.",
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          textFormat: 0,
          version: 1,
        },
      ],
      direction: 'ltr',
      format: '',
      indent: 0,
      version: 1,
    },
  },
  confirmationType: 'message',
  createdAt: '2024-01-01T00:00:00.000Z',
  emails: [
    {
      emailFrom: '"Winning Trimming" <noreply@winningtrimming.com.au>',
      emailTo: '{{email}}',
      message: {
        root: {
          type: 'root',
          children: [
            {
              type: 'paragraph',
              children: [
                {
                  type: 'text',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Thanks for your enquiry — we have received it and will respond shortly.',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
      subject: 'Your enquiry to Winning Trimming',
    },
  ],
  fields: [
    {
      name: 'full-name',
      blockName: 'full-name',
      blockType: 'text',
      label: 'Full Name',
      required: true,
      width: 50,
    },
    {
      name: 'email',
      blockName: 'email',
      blockType: 'email',
      label: 'Email',
      required: true,
      width: 50,
    },
    {
      name: 'phone',
      blockName: 'phone',
      blockType: 'number',
      label: 'Phone',
      required: false,
      width: 50,
    },
    {
      name: 'service',
      blockName: 'service',
      blockType: 'select',
      label: 'Service Required',
      required: true,
      width: 50,
      options: [
        { label: 'Marine', value: 'marine' },
        { label: 'Automotive', value: 'automotive' },
        { label: 'Caravan & RV', value: 'caravan-rv' },
        { label: 'Trade & Industrial', value: 'trade-industrial' },
        { label: 'Commercial Upholstery', value: 'commercial' },
        { label: 'Other / Not sure', value: 'other' },
      ],
    },
    {
      name: 'message',
      blockName: 'message',
      blockType: 'textarea',
      label: 'Project Details',
      required: true,
      width: 100,
    },
  ],
  redirect: undefined,
  submitButtonLabel: 'Request a Quote',
  title: 'Enquiry Form',
  updatedAt: '2024-01-01T00:00:00.000Z',
}
